# Generated by Django 5.2.6 on 2025-12-18 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('service', models.CharField(blank=True, help_text="Services de l'utilisateur séparés par des virgules. Sélectionnez dans la liste. Laissez vide pour les superusers.", max_length=255, null=True, verbose_name='Services autorisés')),
                ('is_active', models.BooleanField(default=False, help_text='Indique si le compte est activé', verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('temporary_password', models.CharField(blank=True, help_text="Mot de passe temporaire haché pour l'activation", max_length=255, null=True, verbose_name='Mot de passe temporaire (haché)')),
                ('activation_token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="Token d'activation")),
                ('token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du token')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserVoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('lang', models.CharField(default='fr-FR', max_length=16)),
                ('voice_name', models.CharField(blank=True, default='', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Preference',
                'verbose_name_plural': 'Voice Preferences',
                'db_table': 'users_voice_preference',
            },
        ),
    ]
