# Generated by Django 5.2.6 on 2026-01-05 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date du dernier changement de mot de passe (pour expiration)', verbose_name='Date du dernier changement de mot de passe'),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de mot de passe',
                'verbose_name_plural': 'Historiques des mots de passe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_passw_user_id_053982_idx')],
            },
        ),
    ]
