# Generated by Django 5.2.6 on 2026-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_changed_at_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le compte a été désactivé', null=True, verbose_name='Date de désactivation'),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Raison pour laquelle le compte a été désactivé (ex: inactivité, sécurité)', null=True, verbose_name='Raison de la désactivation'),
        ),
    ]
