# Generated by Django 5.2.6 on 2026-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deactivated_at_user_deactivation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Date du dernier changement de mot de passe (pour expiration). NULL = premier mot de passe pas encore défini.', null=True, verbose_name='Date du dernier changement de mot de passe'),
        ),
    ]
