# Generated by Django 5.2.6 on 2025-12-18 11:44

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bon_commande', models.CharField(max_length=100, verbose_name='Numéro de bon de commande')),
                ('business_id', models.CharField(blank=True, help_text='Identifiant métier de la ligne modifiée', max_length=500, null=True, verbose_name='ID métier de la ligne')),
                ('item_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name="Référence de l'article")),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ordered Quantity')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantity Delivered')),
                ('quantity_not_delivered', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Quantity Not Delivered')),
                ('cumulative_recipe', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Cumulative Recipe')),
                ('user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Utilisateur')),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date et heure de l'action")),
                ('progress_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name="Taux d'avancement")),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='CompensationLetterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/compensation_letters/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': 'Lettre de compensation',
                'verbose_name_plural': 'Lettres de compensation',
            },
        ),
        migrations.CreateModel(
            name='DelayEvaluationReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/delay_evaluation/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': "Fiche d'évaluation des délais générée",
                'verbose_name_plural': "Fiches d'évaluation des délais générées",
            },
        ),
        migrations.CreateModel(
            name='FichierImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='uploads/', verbose_name='File')),
                ('extension', models.CharField(editable=False, max_length=10, verbose_name='Extension')),
                ('date_importation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Import Date')),
                ('nombre_lignes', models.IntegerField(default=0, editable=False, verbose_name='Number of Rows')),
            ],
            options={
                'verbose_name': 'Imported File',
                'verbose_name_plural': 'Imported Files',
            },
        ),
        migrations.CreateModel(
            name='InitialReceptionBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='ID métier')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Received Quantity')),
                ('montant_total_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Montant total initial')),
                ('montant_recu_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Montant reçu initial')),
                ('taux_avancement_initial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name="Taux d'avancement initial (%)")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Valeur initiale (business)',
                'verbose_name_plural': 'Valeurs initiales (business)',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.CreateModel(
            name='LigneFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.IntegerField(verbose_name='Numéro de ligne')),
                ('contenu', models.JSONField(verbose_name='Contenu de la ligne')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('business_id', models.CharField(blank=True, help_text='Identifiant métier basé sur Order+Line+Item+Schedule', max_length=500, null=True, verbose_name='ID métier')),
            ],
            options={
                'verbose_name': 'Ligne de fichier',
                'verbose_name_plural': 'Lignes de fichiers',
                'ordering': ['fichier', 'numero_ligne'],
            },
        ),
        migrations.CreateModel(
            name='MSRNReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=10, unique=True, verbose_name='Report Number')),
                ('pdf_file', models.FileField(upload_to='msrn_reports/', verbose_name='Fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, help_text='Taux de rétention appliqué (0-100%)', max_digits=20, verbose_name='Taux de rétention (%)')),
                ('retention_cause', models.TextField(blank=True, help_text='Raison de la rétention appliquée', null=True, verbose_name='Cause de la rétention')),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant retenu (calculé automatiquement)', max_digits=20, verbose_name='Montant de la rétention')),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant total à payer après déduction de la rétention', max_digits=20, verbose_name='Montant payable après rétention')),
                ('montant_total_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Montant total au moment de la création du rapport', max_digits=20, null=True, verbose_name='Snapshot - Montant total')),
                ('montant_recu_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Montant reçu au moment de la création du rapport', max_digits=20, null=True, verbose_name='Snapshot - Montant reçu')),
                ('progress_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text="Taux d'avancement au moment de la création du rapport", max_digits=20, null=True, verbose_name="Snapshot - Taux d'avancement")),
                ('retention_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de rétention au moment de la création du rapport', max_digits=20, null=True, verbose_name='Snapshot - Taux de rétention')),
                ('retention_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de rétention au moment de la création du rapport', max_digits=20, null=True, verbose_name='Snapshot - Montant de rétention')),
                ('payable_amount_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payable au moment de la création du rapport', max_digits=20, null=True, verbose_name='Snapshot - Montant payable')),
                ('receptions_data_snapshot', models.JSONField(blank=True, help_text='Snapshot complet des réceptions au moment de la création du rapport', null=True, verbose_name='Snapshot - Données des réceptions')),
                ('payment_terms_snapshot', models.TextField(blank=True, help_text='Payment Terms au moment de la création du rapport', null=True, verbose_name='Snapshot - Payment Terms')),
                ('user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rapport MSRN',
                'verbose_name_plural': 'Rapports MSRN',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumeroBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numéro de bon de commande')),
                ('cpu', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='CPU/Service')),
                ('_montant_total', models.DecimalField(db_column='montant_total', decimal_places=2, default=0, max_digits=20, verbose_name='Montant total (cache)')),
                ('_montant_recu', models.DecimalField(db_column='montant_recu', decimal_places=2, default=0, max_digits=20, verbose_name='Montant reçu (cache)')),
                ('_taux_avancement', models.DecimalField(db_column='taux_avancement', decimal_places=2, default=0, max_digits=20, verbose_name="Taux d'avancement (cache)")),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de rétention (%)')),
                ('retention_cause', models.TextField(blank=True, null=True, verbose_name='Cause de la rétention')),
            ],
            options={
                'verbose_name': 'Numéro de bon de commande',
                'verbose_name_plural': 'Numéros de bons de commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyAmendmentReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/penalty_amendment/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': "Fiche d'amendement de pénalité générée",
                'verbose_name_plural': "Fiches d'amendement de pénalité générées",
            },
        ),
        migrations.CreateModel(
            name='PenaltyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/penalty/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': 'Fiche de pénalité générée',
                'verbose_name_plural': 'Fiches de pénalité générées',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, help_text='Identifiant métier basé sur Order+Line+Item+schedule (doit être unique)', max_length=500, unique=True, verbose_name='ID métier')),
                ('ordered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Ordered Quantity')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Quantity Delivered')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Received Quantity (current file)')),
                ('quantity_not_delivered', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quantity Not Delivered')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Utilisateur')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Unit Price')),
                ('amount_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Delivered')),
                ('amount_not_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount Not Delivered')),
                ('quantity_payable', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Quantity Payable')),
                ('amount_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Montant payable')),
            ],
            options={
                'verbose_name': 'Réception',
                'verbose_name_plural': 'Réceptions',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='TimelineDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_part_mtn', models.IntegerField(default=0, verbose_name='Part MTN (jours)')),
                ('delay_part_force_majeure', models.IntegerField(default=0, verbose_name='Part Force Majeure (jours)')),
                ('delay_part_vendor', models.IntegerField(default=0, verbose_name='Part Fournisseur (jours)')),
                ('quotite_realisee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Quotité réalisée (%)')),
                ('comment_mtn', models.TextField(help_text='Commentaire obligatoire', verbose_name='Commentaire Part MTN')),
                ('comment_force_majeure', models.TextField(help_text='Commentaire obligatoire', verbose_name='Commentaire Part Force Majeure')),
                ('comment_vendor', models.TextField(help_text='Commentaire obligatoire', verbose_name='Commentaire Part Fournisseur')),
                ('retention_amount_timeline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Montant Rétention Timeline')),
                ('retention_rate_timeline', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux Rétention Timeline (%)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Timeline Delay',
                'verbose_name_plural': 'Timeline Delays',
            },
        ),
        migrations.CreateModel(
            name='VendorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='Fournisseur')),
                ('delivery_compliance', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Delivery Compliance to Order (Quantity & Quality)')),
                ('delivery_timeline', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Delivery Execution Timeline')),
                ('advising_capability', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Vendor Advising Capability')),
                ('after_sales_qos', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='After Sales Services QOS')),
                ('vendor_relationship', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Vendor Relationship')),
                ('vendor_final_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moyenne des 5 critères (calculée automatiquement)', max_digits=4, verbose_name='Vendor Final Rating')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Évaluation fournisseur',
                'verbose_name_plural': 'Évaluations fournisseurs',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
