# Generated by Django 5.2.6 on 2025-11-06 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichierimporte',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='fichier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.fichierimporte', verbose_name='Fichier importé'),
        ),
        migrations.AddField(
            model_name='initialreceptionbusiness',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_reception_lines', to='orders.fichierimporte', verbose_name='Fichier source'),
        ),
        migrations.AddField(
            model_name='lignefichier',
            name='fichier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.fichierimporte', verbose_name="Fichier d'origine"),
        ),
        migrations.AddField(
            model_name='numeroboncommande',
            name='fichiers',
            field=models.ManyToManyField(related_name='bons_commande', to='orders.fichierimporte', verbose_name='Fichiers associés'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msrn_reports', to='orders.numeroboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='initialreceptionbusiness',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_reception_lines', to='orders.numeroboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='reception',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='orders.numeroboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='reception',
            name='fichier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='orders.fichierimporte', verbose_name='Fichier importé'),
        ),
        migrations.AddField(
            model_name='timelinedelay',
            name='bon_commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_delay', to='orders.numeroboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='vendorevaluation',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_evaluations', to='orders.numeroboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='vendorevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur'),
        ),
        migrations.AddIndex(
            model_name='lignefichier',
            index=models.Index(fields=['fichier', 'numero_ligne'], name='orders_lign_fichier_165fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='lignefichier',
            index=models.Index(fields=['business_id'], name='orders_lign_busines_33b1f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lignefichier',
            unique_together={('fichier', 'numero_ligne')},
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['bon_commande', 'fichier'], name='orders_rece_bon_com_9eac98_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['date_modification'], name='orders_rece_date_mo_b66e0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorevaluation',
            unique_together={('bon_commande', 'supplier')},
        ),
    ]
