# Generated by Django 5.2.6 on 2025-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lignefichier',
            name='ligne_fichier_bid_idx',
        ),
        migrations.RemoveIndex(
            model_name='reception',
            name='reception_bon_qty_idx',
        ),
        migrations.AlterField(
            model_name='lignefichier',
            name='business_id',
            field=models.CharField(blank=True, help_text='Identifiant métier basé sur Order+Line+Item+Schedule', max_length=500, null=True, verbose_name='ID métier'),
        ),
        migrations.AlterField(
            model_name='msrnreport',
            name='report_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Report Number'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='business_id',
            field=models.CharField(db_index=True, help_text='Identifiant métier basé sur Order+Line+Item+schedule (doit être unique)', max_length=500, unique=True, verbose_name='ID métier'),
        ),
    ]
