# Generated by Django 5.2.6 on 2025-10-28 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinedelay',
            name='quotite_realisee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Quotité réalisée (%)'),
        ),
    ]
