# Generated by Django 5.2.6 on 2025-11-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefichier',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='orders.fichierimporte', verbose_name="Fichier d'origine"),
        ),
        migrations.AlterField(
            model_name='reception',
            name='fichier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions', to='orders.fichierimporte', verbose_name='Fichier importé'),
        ),
    ]
