# Generated by Django 5.2.6 on 2026-01-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msrnreport',
            name='cpu_snapshot',
            field=models.CharField(blank=True, db_index=True, help_text='CPU au moment de la création', max_length=100, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='gm_epmo_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GM EPMO'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='manager_portfolio_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Portfolio'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='project_coordinator_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Coordinator'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='project_manager_snapshot',
            field=models.CharField(blank=True, db_index=True, help_text='Nom du Project Manager', max_length=255, null=True, verbose_name='Project Manager'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='senior_pm_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senior PM'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='senior_technical_lead_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senior Technical Lead'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='supplier_snapshot',
            field=models.CharField(blank=True, db_index=True, help_text='Nom du fournisseur au moment de la création', max_length=500, null=True, verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='msrnreport',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours de signature'), ('completed', 'Toutes signatures obtenues'), ('cancelled', 'Annulé')], db_index=True, default='draft', max_length=20, verbose_name='Statut du workflow'),
        ),
        migrations.CreateModel(
            name='MSRNSignatureTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_role', models.CharField(choices=[('project_manager', 'Project Manager'), ('project_coordinator', 'Project Coordinator'), ('senior_pm', 'Senior PM'), ('senior_technical_lead', 'Senior Technical Lead'), ('manager_portfolio', 'Manager Portfolio'), ('gm_epmo', 'GM EPMO')], max_length=50, verbose_name='Rôle du signataire')),
                ('signatory_name', models.CharField(help_text='Nom complet du signataire', max_length=255, verbose_name='Nom du signataire')),
                ('date_sent', models.DateTimeField(blank=True, help_text='Date à laquelle le document a été envoyé au signataire', null=True, verbose_name="Date d'envoi")),
                ('date_received', models.DateTimeField(blank=True, help_text='Date à laquelle le signataire a signé/retourné le document', null=True, verbose_name='Date de réception/signature')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('received', 'Reçu/Signé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('comments', models.TextField(blank=True, help_text='Remarques ou observations sur cette signature', null=True, verbose_name='Commentaires')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordre dans le workflow de signature (1=premier signataire)', verbose_name='Ordre de signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.CharField(blank=True, help_text='Utilisateur ayant effectué la dernière modification', max_length=150, null=True, verbose_name='Modifié par')),
                ('msrn_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_tracking', to='orders.msrnreport', verbose_name='Rapport MSRN')),
            ],
            options={
                'verbose_name': 'Suivi de signature MSRN',
                'verbose_name_plural': 'Suivis de signatures MSRN',
                'ordering': ['msrn_report', 'order', 'signatory_role'],
                'unique_together': {('msrn_report', 'signatory_role')},
            },
        ),
    ]
