# Generated by Django 5.2.6 on 2025-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_lignefichier_ligne_fichier_bid_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msrnreport',
            name='payment_terms_snapshot',
            field=models.TextField(blank=True, help_text='Payment Terms au moment de la création du rapport', null=True, verbose_name='Snapshot - Payment Terms'),
        ),
    ]
