# Generated by Django 5.2.6 on 2025-11-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_lignefichier_fichier_alter_reception_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialreceptionbusiness',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_reception_lines', to='orders.fichierimporte', verbose_name='Fichier source'),
        ),
        migrations.CreateModel(
            name='CompensationLetterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/compensation_letters/', verbose_name='Fichier PDF')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_letters', to='orders.numeroboncommande', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Lettre de compensation',
                'verbose_name_plural': 'Lettres de compensation',
            },
        ),
        migrations.CreateModel(
            name='DelayEvaluationReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/delay_evaluation/', verbose_name='Fichier PDF')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_evaluation_reports', to='orders.numeroboncommande', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': "Fiche d'évaluation des délais générée",
                'verbose_name_plural': "Fiches d'évaluation des délais générées",
            },
        ),
        migrations.CreateModel(
            name='PenaltyAmendmentReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/penalty_amendment/', verbose_name='Fichier PDF')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_amendment_reports', to='orders.numeroboncommande', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': "Fiche d'amendement de pénalité générée",
                'verbose_name_plural': "Fiches d'amendement de pénalité générées",
            },
        ),
        migrations.CreateModel(
            name='PenaltyReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/penalty/', verbose_name='Fichier PDF')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_reports', to='orders.numeroboncommande', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Fiche de pénalité générée',
                'verbose_name_plural': 'Fiches de pénalité générées',
            },
        ),
    ]
