# Generated by Django 5.2.6 on 2026-01-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_msrn_signature_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msrnsignaturetracking',
            options={'ordering': ['msrn_report', 'order'], 'verbose_name': 'Signature MSRN', 'verbose_name_plural': 'Signatures MSRN'},
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date signé'),
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='signatory_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='signatory_role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('project_coordinator', 'Project Coordinator'), ('senior_pm', 'Senior PM'), ('senior_technical_lead', 'Senior Technical Lead'), ('manager_portfolio', 'Manager Portfolio'), ('gm_epmo', 'GM EPMO')], max_length=50, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('signed', 'Signé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
