# Generated by Django 5.2.6 on 2026-01-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_simplify_signature_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='msrnsignaturetracking',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Date du dernier email de rappel envoyé', null=True, verbose_name='Dernier rappel envoyé'),
        ),
        migrations.AddField(
            model_name='msrnsignaturetracking',
            name='signatory_email',
            field=models.EmailField(blank=True, help_text="Email alternatif si pas d'utilisateur lié", max_length=255, null=True, verbose_name='Email du signataire'),
        ),
        migrations.AddField(
            model_name='msrnsignaturetracking',
            name='signatory_user',
            field=models.ForeignKey(blank=True, help_text='Lier à un utilisateur pour recevoir les alertes email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msrn_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signataire'),
        ),
    ]
