# Generated by Django 5.2.6 on 2026-01-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_add_signature_reminder_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='signatory_email',
        ),
        migrations.RemoveField(
            model_name='msrnsignaturetracking',
            name='signatory_user',
        ),
    ]
