# Generated by Django 5.2.6 on 2026-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_msrnsignaturetracking_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msrnreport',
            name='report_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Report Number'),
        ),
    ]
