# Generated by Django 5.2.6 on 2026-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_msrnreport_report_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='msrnreport',
            name='currency_snapshot',
            field=models.CharField(blank=True, help_text='Devise du bon de commande au moment de la création du rapport', max_length=10, null=True, verbose_name='Snapshot - Devise'),
        ),
    ]
