# Generated by Django 5.2.6 on 2026-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_msrnreport_currency_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='msrnreport',
            name='vendor_snapshot',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Vendor (Supplier)'),
        ),
        migrations.AlterField(
            model_name='msrnsignaturetracking',
            name='signatory_role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('project_coordinator', 'Project Coordinator'), ('senior_pm', 'Senior PM'), ('senior_technical_lead', 'Senior Technical Lead'), ('manager_portfolio', 'Manager Portfolio'), ('gm_epmo', 'GM EPMO'), ('vendor', 'Vendor')], max_length=50, verbose_name='Rôle'),
        ),
    ]
